name: rsocket
version: 0.0.1
description: RSocket for Dart
homepage: https://github.com/rsocket/rsocket-dart
repository: https://github.com/rsocket/rsocket-dart.git
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  rxdart: ^0.24.1
dev_dependencies:
  test: ^1.6.0
